import {Router} from "express";
import { createChatMessage,getChatMessage,getRecentChats,deleteChat, searchChat } from "../controllers/chat.controller.js";
import { authenticate } from "../middleware/auth.middleware.js";
const router=Router();
router.use(authenticate);
router.post("/",createChatMessage);
router.get("/recent", getRecentChats);
router.get("/search",searchChat);
router.get("/:chatId/messages",getChatMessage);
router.delete("/:chatId", deleteChat);
export default router;